#
#    AddOre Configuration
#
#    To spawn ore into a world, you must define a generator config block.
#    A generator config block has a root name unique to it, and the following options under it:
#        ore_id
#        spawns_in_id
#        gens_per_chunk
#        max_y
#        y_modifier
#        max_x
#        x_modifier
#        max_z
#        z_modifier
#        deposit_size
#        run_order
#        worlds
#
#    These options in a bit more detail:
#        ore_id           - This is the id of the block of ore you wish to spawn
#        spawns_in_id     - This is the id of the block your ore can spawn in
#        gens_per_chunk   - This is how many attempts will be made at randomly placing this ore in one chunk
#        max_y            - This is the maximum number for a y value to be fed to the random number generator, which will generate a number to be used from 0 (inclusive) to this number (exclusive)
#        y_modifier       - This is a number to be added to the result of the random number generation from max_y
#            NOTE: This means that if you wanted to make an ore that spawned from 5 to 20, max_y would be 16, and y_modifier would be 5
#        max_x            - This is the maximum number for a x value in a chunk to be fed to the random number generator (see also max_y)
#        x_modifier       - This is a number to be added to the result from the random number generation from max_x
#        max_z            - Same as max_x but for z
#        z_modifier       - Same as x_modifier but for z
#            NOTE: max_x and max_z are typically 16, x_modifier and z_modifier are typically 0
#        deposit_size     - This is semi-magical value that has to do with how the minecraft server spawns ores, generally larger numbers means a larger deposit
#            NOTE: You can look at the example configurations that come from the minecraft default ore spawning to get an idea of what to use
#        run_order        - This is a value that indicates when this generator should run, compared to others defined here, higher values run before smaller values
#        worlds           - This is a list of worlds in which this generator will be run
#
#    A generator is given an internal id number based off ore_id, spawns_in_id, gens_per_chunk, max_y, y_modifier, max_x, x_modifier, max_z, z_modifier, and deposit_size.
#    Changing any of these values will cause AddOre to consider this a "new" generator and generate in any specified worlds again, this may cause unwanted behavior.
#    IT IS HIGHLY SUGGESTED YOU TEST THE ORE GENERATION SETTINGS ON A TEST SERVER, THEN RUN IT ON A PRODUCTION SERVER.
#
#####
#
#    Example configuration to add quartz to a nether world
#
#putquartz:
#    ore_id: 153
#    spawns_in_id: 87
#    gens_per_chunk: 16
#    max_y: 108
#    y_modifier: 10
#    max_x: 16
#    x_modifier: 0
#    max_z: 16
#    z_modifier: 0
#    deposit_size: 13
#    run_order: 0
#    worlds:
#        - world_nether
#
#####
#
#    Example configuration to add iron ore to an overworld
#
#putiron:
#    ore_id: 15
#    spawns_in_id: 1
#    gens_per_chunk: 20
#    max_y: 64
#    y_modifier: 0
#    max_x: 16
#    x_modifier: 0
#    max_z: 16
#    z_modifier: 0
#    deposit_size: 8
#    run_order: 0
#    worlds:
#        - world
#
#####
#
#    Example configuration to add gold ore to an overworld
#
#putgold:
#    ore_id: 14
#    spawns_in_id: 1
#    gens_per_chunk: 2
#    max_y: 32
#    y_modifier: 0
#    max_x: 16
#    x_modifier: 0
#    max_z: 16
#    z_modifier: 0
#    deposit_size: 8
#    run_order: 0
#    worlds:
#        - world
#
#####
#
#    Example configuration to add coal ore to an overworld
#
#putcoal:
#    ore_id: 16
#    spawns_in_id: 1
#    gens_per_chunk: 20
#    max_y: 128
#    y_modifier: 0
#    max_x: 16
#    x_modifier: 0
#    max_z: 16
#    z_modifier: 0
#    deposit_size: 16
#    run_order: 0
#    worlds:
#        - world
#
#####
#
#    Example configuration to add diamond ore to an overworld
#
#putdiamond:
#    ore_id: 56
#    spawns_in_id: 1
#    gens_per_chunk: 1
#    max_y: 16
#    y_modifier: 0
#    max_x: 16
#    x_modifier: 0
#    max_z: 16
#    z_modifier: 0
#    deposit_size: 7
#    run_order: 0
#    worlds:
#        - world
#
#####
#
#    Example configuration to add lapis ore to an overworld
#    NOTE: Because of a slight variation lapis takes from standard, this is not 100% perfect vanilla emulation
#
#putlapis:
#    ore_id: 21
#    spawns_in_id: 1
#    gens_per_chunk: 1
#    max_y: 32
#    y_modifier: 0
#    max_x: 16
#    x_modifier: 0
#    max_z: 16
#    z_modifier: 0
#    deposit_size: 6
#    run_order: 0
#    worlds:
#        - world
#
#####
#
#    Example configuration to add redstone ore to an overworld
#
#putredstone:
#    ore_id: 73
#    spawns_in_id: 1
#    gens_per_chunk: 8
#    max_y: 16
#    y_modifier: 0
#    max_x: 16
#    x_modifier: 0
#    max_z: 16
#    z_modifier: 0
#    deposit_size: 7
#    run_order: 0
#    worlds:
#        - world
#
#####
#
#    Example configuration to add dirt to an overworld
#
#putdirt:
#    ore_id: 3
#    spawns_in_id: 1
#    gens_per_chunk: 20
#    max_y: 128
#    y_modifier: 0
#    max_x: 16
#    x_modifier: 0
#    max_z: 16
#    z_modifier: 0
#    deposit_size: 32
#    run_order: 0
#    worlds:
#        - world
#
